version: 1.0.0-CI{build}
configuration: Release
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $env:LABEL = "CI" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: $env:CORRECTED_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION -replace "-CI[0-9]*$","-$env:LABEL"
- ps: Update-AppveyorBuild -Version $env:CORRECTED_BUILD_VERSION
nuget:
  account_feed: true
before_build:
- msbuild.exe /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Version=%CORRECTED_BUILD_VERSION% /v:minimal /t:restore
build_script:
- msbuild.exe /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Version=%CORRECTED_BUILD_VERSION% /v:minimal /t:build
after_build:
- msbuild.exe /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Version=%CORRECTED_BUILD_VERSION%;IncludeSymbols=true;IncludeSource=true /v:minimal /t:pack
test:
  categories:
    except:
      - UNSAFE
artifacts:
- path: '**\*.nupkg'
cache:
- '%USERPROFILE%\.nuget\packages'