version: '1.0.0-CI{build}'
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $env:LABEL = "CI" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: $env:CORRECTED_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION -replace "-CI[0-9]*$","-$env:LABEL"
- ps: Update-AppveyorBuild -Version $env:CORRECTED_BUILD_VERSION
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet --info
- dotnet build "src/**/project.json" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack "src/ApacheOrcDotNet" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test "test/ApacheOrcDotNet.Test"
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'